# Generated by Django 2.2.6 on 2019-10-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moonlight',
            name='langt',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='moonlight',
            name='longt',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
