# Generated by Django 2.2.6 on 2019-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('longt', models.DecimalField(decimal_places=20, max_digits=30)),
                ('langt', models.DecimalField(decimal_places=20, max_digits=30)),
                ('call', models.CharField(max_length=100)),
            ],
        ),
    ]
